# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.
on:
  schedule:
    # Every 6 hours
    - cron: "0 */6 * * *"
  
  # The action can also be triggered manually from the Actions tab
  workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    # Checks out the repo under $GITHUB_WORKSPACE so your job can access it
    - uses: actions/checkout@v2

    # Generates the snake
    - uses: Platane/snk@v3
      id: snake-gif
      with:
        github_user_name: ahmed5145
        # these next 2 lines generate the files in the dist folder
        gif_out_path: dist/github-contribution-grid-snake.gif
        svg_out_path: dist/github-contribution-grid-snake.svg

    # Show the status of the build to make it easier for debugging
    - run: git status

    # Push the changes to the repository
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        force: true

    # Push the generated content to the output branch for GitHub Pages
    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.1.3
      with:
        target_branch: output
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
