name: Generate Snake Eating My Contributions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Platane SNK tool
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Platane SNK
      run: |
        npm install -g platane-snk

    # Generate the Snake SVG
    - name: Generate Snake SVG
      run: |
        snk --github-user ahmed5145 --output dist/snake.svg

    # Commit and push the generated Snake SVG
    - name: Commit and Push Snake SVG
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "ahmedmohamed200354@gmail.com"
        git add dist/snake.svg
        git commit -m "Add updated snake SVG"
        git push
