name: Generate Snake Eating My Contributions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Generate Snake SVG from Platane
    - name: Generate Snake Eating My Contributions
      uses: Platane/snk@v3
      with:
        github_user_name: ahmed5145 # Replace with your GitHub username
        outputs: |
          dist/github-snake.svg
          dist/github-snake-dark.svg?palette=github-dark

    # Commit and push the generated Snake SVG
    - name: Commit and Push Snake SVG
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "ahmedmohamed200354@gmail.com"
        git add dist/github-snake.svg
        git add dist/github-snake-dark.svg
        git commit -m "Add snake eating contributions"
        git push
