name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout
        uses: actions/checkout@v3

      # Set up Node.js 20 explicitly (to avoid deprecation warning)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Generate the snake SVG
      - name: Generate Snake SVG
        id: snake
        uses: Platane/snk@v2
        with:
          github_user_name: ahmed5145
          outputs: dist/snake.svg

      # Upload the generated SVG to the repository
      - name: Upload Snake SVG
        run: |
          mkdir -p dist
          mv dist/snake.svg dist/
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add dist/snake.svg
          git commit -m "chore: update snake contribution graph" || echo "No changes to commit"
          git push
