name: Generate and Push Snake SVG

on:
  push:
    branches:
      - main

jobs:
  generate-snake-svg:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Generate the Snake SVG
      - name: Generate Snake SVG
        uses: Platane/snk@v2
        with:
          github_user_name: ahmed5145  # Your GitHub username
          outputs: dist/snake.svg  # Path to save the generated SVG

      # Commit and Push the SVG
      - name: Commit and Push Snake SVG
        run: |
          git config --global user.name "ahmed5145"
          git config --global user.email "ahmedmohamed200354@gmail.com"
          git add dist/snake.svg
          git commit -m "Add updated snake SVG"
          git push
