# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.
on:
  schedule:
    # Every 6 hours
    - cron: "0 */6 * * *"

  # This allows manual trigger from the Actions tab
  workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v2

      # Generate the snake image
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ahmed5145
          # Output file paths for snake images
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Show status of the build (useful for debugging)
      - run: git status

      # Push the changes (generated snake images) back to the repository
      - name: Push changes
        uses: ad-m/github-push-action@v0.6
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: main  # Change this to your target branch if needed
          force: true

      # Use GitHub Pages to serve the generated images (optional step)
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # The output branch where the images are saved
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
